# fastNLP中的 Vocabulary
## 构建 Vocabulary

In [16]:
from fastNLP import Vocabulary

vocab = Vocabulary()
vocab.add_word_lst(['复', '旦', '大', '学'])  # 加入新的字
vocab.add_word('上海')  # `上海`会作为一个整体
vocab.to_index('复')  # 应该会为3
vocab.to_index('我')  # 会输出1，Vocabulary中默认pad的index为0, unk(没有找到的词)的index为1

#  在构建target的Vocabulary时，词表中应该用不上pad和unk，可以通过以下的初始化
vocab = Vocabulary(unknown=None, padding=None)

In [17]:
vocab

Vocabulary([]...)

In [18]:
vocab.add_word_lst(['positive', 'negative'])

Vocabulary(['positive', 'negative']...)

In [19]:
vocab.to_index('positive')

0

### 没有设置 unk 的情况

In [20]:
vocab.to_index('neutral')  # 会报错，因为没有unk这种情况

ValueError: word `neutral` not in vocabulary

### 设置 unk 的情况

In [25]:
from fastNLP import Vocabulary

vocab = Vocabulary(unknown='<unk>', padding=None)
vocab.add_word_lst(['positive', 'negative'])
vocab.to_index('neutral'), vocab.to_word(vocab.to_index('neutral'))

(0, '<unk>')

In [8]:
vocab

Vocabulary(['positive', 'negative']...)

In [23]:
from fastNLP import Vocabulary
from fastNLP import DataSet

dataset = DataSet({'chars': [
                                ['今', '天', '天', '气', '很', '好', '。'],
                                ['被', '这', '部', '电', '影', '浪', '费', '了', '两', '个', '小', '时', '。']
                            ],
                    'target': ['neutral', 'negative']
})

vocab = Vocabulary()
vocab.from_dataset(dataset, field_name='chars')
print(dataset)

+-------------------------------------------------+----------+
| chars                                           | target   |
+-------------------------------------------------+----------+
| ['今', '天', '天', '气', '很', '好', '。']      | neutral  |
| ['被', '这', '部', '电', '影', '浪', '费', '... | negative |
+-------------------------------------------------+----------+


In [24]:
vocab.index_dataset(dataset, field_name='chars')
print(dataset)
vocab

+-------------------------------------------------+----------+
| chars                                           | target   |
+-------------------------------------------------+----------+
| [4, 2, 2, 5, 6, 7, 3]                           | neutral  |
| [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1... | negative |
+-------------------------------------------------+----------+


Vocabulary(['今', '天', '气', '很', '好']...)

In [26]:
target_vocab = Vocabulary(padding=None, unknown=None)
target_vocab.from_dataset(dataset, field_name='target')
target_vocab.index_dataset(dataset, field_name='target')
print(dataset)
target_vocab

+-------------------------------------------------+--------+
| chars                                           | target |
+-------------------------------------------------+--------+
| [4, 2, 2, 5, 6, 7, 3]                           | 0      |
| [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1... | 1      |
+-------------------------------------------------+--------+


Vocabulary([0, 1]...)

In [28]:
from fastNLP import Vocabulary
from fastNLP import DataSet

tr_data = DataSet({'chars': [
                               ['今', '天', '心', '情', '很', '好', '。'],
                               ['被', '这', '部', '电', '影', '浪', '费', '了', '两', '个', '小', '时', '。']
                           ],
                   'target': ['positive', 'negative']
})
dev_data = DataSet({'chars': [
                               ['住', '宿', '条', '件', '还', '不', '错'],
                               ['糟', '糕', '的', '天', '气', '，', '无', '法', '出', '行', '。']
                           ],
                   'target': ['positive', 'negative']
})

vocab = Vocabulary()
#  将验证集或者测试集在建立词表是放入no_create_entry_dataset这个参数中。
vocab.from_dataset(tr_data, field_name='chars', no_create_entry_dataset=[dev_data])
print(tr_data)
print(vocab)

+-------------------------------------------------+----------+
| chars                                           | target   |
+-------------------------------------------------+----------+
| ['今', '天', '心', '情', '很', '好', '。']      | positive |
| ['被', '这', '部', '电', '影', '浪', '费', '... | negative |
+-------------------------------------------------+----------+
Vocabulary(['今', '天', '心', '情', '很']...)


In [29]:
vocab.index_dataset(tr_data, field_name="chars")
tr_data

+-------------------------------------------------+----------+
| chars                                           | target   |
+-------------------------------------------------+----------+
| [4, 3, 5, 6, 7, 8, 2]                           | positive |
| [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, ... | negative |
+-------------------------------------------------+----------+

In [30]:
import torch
from fastNLP.embeddings import StaticEmbedding
from fastNLP import Vocabulary

vocab = Vocabulary()
vocab.add_word('train')
vocab.add_word('only_in_train')  # 仅在train出现，但肯定在预训练词表中不存在
vocab.add_word('test', no_create_entry=True)  # 该词只在dev或test中出现
vocab.add_word('only_in_test', no_create_entry=True)  # 这个词在预训练的词表中找不到

embed = StaticEmbedding(vocab, model_dir_or_name='en-glove-6b-50d')
print(embed(torch.LongTensor([vocab.to_index('train')])))
print(embed(torch.LongTensor([vocab.to_index('only_in_train')])))
print(embed(torch.LongTensor([vocab.to_index('test')])))
print(embed(torch.LongTensor([vocab.to_index('only_in_test')])))
print(embed(torch.LongTensor([vocab.unknown_idx])))

  0%|          | 81.9k/63.5M [00:00<01:21, 779kB/s]

http://212.129.155.247/embedding/glove.6B.50d.zip not found in cache, downloading to /var/folders/1t/r3byrg0s5cb80qkz17dn8nc40000gn/T/tmpn42uwexj


100%|██████████| 63.5M/63.5M [01:30<00:00, 701kB/s]


Finish download from http://212.129.155.247/embedding/glove.6B.50d.zip
Copy file to /Users/mac/.fastNLP/embedding/glove.6B.50d
Found 2 out of 6 words in the pre-training embedding.
tensor([[ 0.9497,  0.3433,  0.8450, -0.8852, -0.7208, -0.2931, -0.7468,  0.6512,
          0.4730, -0.7401,  0.1877, -0.3828, -0.5590,  0.4295, -0.2698, -0.4238,
         -0.3124,  1.3423, -0.7857, -0.6302,  0.9182,  0.2113, -0.5744,  1.4549,
          0.7546, -1.6165, -0.0085,  0.0029,  0.5130, -0.4745,  2.5306,  0.8594,
         -0.3067,  0.0578,  0.6623,  0.2080,  0.6424, -0.5246, -0.0534,  1.1404,
         -0.1370, -0.1836,  0.4546, -0.5096, -0.0255, -0.0286,  0.1805, -0.4483,
          0.4053, -0.3682]], grad_fn=<EmbeddingBackward>)
tensor([[ 0.0111, -0.0065,  0.2143,  0.1087, -0.0059, -0.1832, -0.2404, -0.0755,
          0.0891, -0.1011,  0.2368,  0.1285, -0.1689, -0.1007,  0.0905, -0.1177,
         -0.0937,  0.1927, -0.1697, -0.2049,  0.0824,  0.2177,  0.0522, -0.0614,
         -0.0936, -0.1448,  0.20

/Users/distiller/project/conda/conda-bld/pytorch_1591914925853/work/aten/src/ATen/native/TensorFactories.cpp:361: UserWarning: Deprecation warning: In a future PyTorch release torch.full will no longer return tensors of floating dtype by default. Instead, a bool fill_value will return a tensor of torch.bool dtype, and an integral fill_value will return a tensor of torch.long dtype. Set the optional `dtype` or `out` arguments to suppress this warning.


In [31]:
vocab.to_index('train')

2

In [32]:
torch.LongTensor([vocab.to_index('train')])

tensor([2])

In [33]:
print(embed(torch.LongTensor([vocab.to_index('train')])))

tensor([[ 0.9497,  0.3433,  0.8450, -0.8852, -0.7208, -0.2931, -0.7468,  0.6512,
          0.4730, -0.7401,  0.1877, -0.3828, -0.5590,  0.4295, -0.2698, -0.4238,
         -0.3124,  1.3423, -0.7857, -0.6302,  0.9182,  0.2113, -0.5744,  1.4549,
          0.7546, -1.6165, -0.0085,  0.0029,  0.5130, -0.4745,  2.5306,  0.8594,
         -0.3067,  0.0578,  0.6623,  0.2080,  0.6424, -0.5246, -0.0534,  1.1404,
         -0.1370, -0.1836,  0.4546, -0.5096, -0.0255, -0.0286,  0.1805, -0.4483,
          0.4053, -0.3682]], grad_fn=<EmbeddingBackward>)


In [34]:
embed

StaticEmbedding(
  (dropout_layer): Dropout(p=0, inplace=False)
  (embedding): Embedding(5, 50, padding_idx=0)
)

In [41]:
print(embed(torch.LongTensor([5])))

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]], grad_fn=<EmbeddingBackward>)
